task_config:
  dataset_dir: &dataset_dir '/data/insertion_puzzle/'  # relative to project folder
  episode_len: &episode_len 100
  state_dim: &state_dim 8
  action_dim: &action_dim 8
  cam_width: &cam_width 320
  cam_height: &cam_height 240
  camera_names: &camera_names [ 'front' ]

policy_config:
  lr: 0.00001
  policy_class: 'Diffusion'
  camera_names: *camera_names
  num_queries: 30
  vq: False
  ema_power: 0.75
  observation_horizon: 1
  action_horizon: 8
  prediction_horizon: 30
  num_inference_timesteps: 10
  state_dim: *state_dim
  action_dim: *action_dim

train_config:
  seed: 42
  num_epochs: 20000
  batch_size_val: 8
  batch_size_train: 8
  best_val_loss: "loss"  # l1_loss or l2_loss
  eval_ckpt_name: 'best_ckpt_epoch_31.ckpt'
  checkpoint_dir: '/checkpoints/diffusion_11-30_06-28/'  # relative to project folder
  wandb: True


