task_config:
  dataset_dir: &dataset_dir '/data/insertion_puzzle_aligned/'
  episode_len: &episode_len 160
  state_dim: &state_dim 8
  action_dim: &action_dim 8
  cam_width: &cam_width 320
  cam_height: &cam_height 240
  camera_names: &camera_names [ 'front', 'static']

policy_config:
  policy_class: 'ACT'
  camera_names: *camera_names
  lr: 0.00001
  num_queries: 30
  kl_weight: 10
  hidden_dim: 512
  dim_feedforward': 3200
  lr_backbone: 0.00001
  backbone: 'resnet18'
  enc_layers: 4
  dec_layers: 7
  nheads: 8
  temporal_agg: True
  state_dim: *state_dim
  action_dim: *action_dim

train_config:
  seed: 42
  num_epochs: 500000
  batch_size_val: 8
  batch_size_train: 8
  best_val_loss: "loss"  # l1_loss or l2_loss
  checkpoint_dir: '/checkpoints/insertion_puzzle/'  # relative to project folder
  eval_ckpt_dir: '/checkpoints/insertion_puzzle/puz_act_00-32_01-18/eval/'
  eval_ckpt_name: 'best_ckpt_epoch_89140.ckpt'
  wandb: True


